# Generated by Django 4.1.7 on 2023-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(default=dict),
        ),
    ]
