# Generated by Django 4.1.7 on 2023-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0002_alter_check_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
